// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbkI8uwv1xVSlIVV3I2dILxs9-foMdNgY',
    appId: '1:242720635019:web:4663bbc67352c57d363c8e',
    messagingSenderId: '242720635019',
    projectId: 'geetaxi-15c74',
    authDomain: 'geetaxi-15c74.firebaseapp.com',
    databaseURL: 'https://geetaxi-15c74.firebaseio.com',
    storageBucket: 'geetaxi-15c74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuF-MWNKVreYgafFGSjcixUZVw0kgTkvw',
    appId: '1:242720635019:android:534c621784e13938363c8e',
    messagingSenderId: '242720635019',
    projectId: 'geetaxi-15c74',
    databaseURL: 'https://geetaxi-15c74.firebaseio.com',
    storageBucket: 'geetaxi-15c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4gUR24k17vQbTopxbv7To92QfKqH2QM4',
    appId: '1:242720635019:ios:307dac81d10937f4363c8e',
    messagingSenderId: '242720635019',
    projectId: 'geetaxi-15c74',
    databaseURL: 'https://geetaxi-15c74.firebaseio.com',
    storageBucket: 'geetaxi-15c74.appspot.com',
    iosClientId: '242720635019-74t4a7pb5ppcvb0hri1h082uae7shfa4.apps.googleusercontent.com',
    iosBundleId: 'com.fapp4you.lokaluser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4gUR24k17vQbTopxbv7To92QfKqH2QM4',
    appId: '1:242720635019:ios:307dac81d10937f4363c8e',
    messagingSenderId: '242720635019',
    projectId: 'geetaxi-15c74',
    databaseURL: 'https://geetaxi-15c74.firebaseio.com',
    storageBucket: 'geetaxi-15c74.appspot.com',
    iosClientId: '242720635019-74t4a7pb5ppcvb0hri1h082uae7shfa4.apps.googleusercontent.com',
    iosBundleId: 'com.fapp4you.lokaluser',
  );
}
